#!/bin/bash

#BSUB -J   TF
#BSUB -W   00:40
#BSUB -cwd '/home/bsc31/bsc31093'
#BSUB -oo  '/home/bsc31/bsc31093/tf_SN_%J.out'
#BSUB -eo  '/home/bsc31/bsc31093/tf_SN_%J.err'
#BSUB -x
#BSUB -n   17
#BSUB -R   'span[ptile=1]'

  echo "------------- Hecuba app nodes config file  --------------"
  CURR_DIR=`pwd`
  export APPPATH=$CURR_DIR/test_tf
  PYTHON_APP=$APPPATH/inference_pycompss.py
  API_PATH=$APPPATH/
  CASSANDRA_MODULE_PATH=/gpfs/scratch/bsc31/bsc31093/apache-cassandra-3.4/module

  module load MKL/2017.0.098
  module unload PYTHON/2.7.6
  module load PYTHON/2.7.12_ML
  export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

  echo "------------------- pythonpath: cassandra python driver -------------------"
  export PYTHONPATH=$CURR_DIR/.local/lib/python2.7/site-packages/futures-3.0.3-py2.7.egg:$PYTHONPATH

  echo "------------------- pythonpath:Hecuba requirements -------------------"
  export PYTHONPATH=$API_PATH:$APPPATH:$PYTHONPATH

  echo "------------------- Get job nodes  -----------------"
  HOSTSARRAY=($LSB_HOSTS) 
  CLIENTHOST=${HOSTSARRAY[0]} #1st node for client 
  DSNODES=${HOSTSARRAY[@]:1}  #rest of nodes for DS

  echo "----------------- Launching enqueue_compss -----------------"
  launch_compss \
  --tasks_per_node=16 \
  --master_node=$CLIENTHOST \
  --worker_nodes="$DSNODES" \
  --lang=python \
  --network=infiniband \
  --debug \
  --tracing \
  --pythonpath=$PYTHONPATH \
  $PYTHON_APP

